AllCops:
  SuggestExtensions: false

require:
  - standard
  - standard-custom
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml

Style/ArgumentsForwarding:
  Enabled: false