ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "CSV"
  inflect.acronym "HTML"
  inflect.acronym "JSON"
  inflect.acronym "JSONL"
  inflect.acronym "LLM"
  inflect.acronym "PDF"
  inflect.acronym "OpenAI"
  inflect.acronym "OpenAIResponse"
  inflect.acronym "OpenAIMessage"
  inflect.acronym "MistralAI"
  inflect.acronym "MistralAIResponse"
  inflect.acronym "MistralAIMessage"
  inflect.acronym "GoogleVertexAI"
  inflect.acronym "VertexAI"
end
